import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_assignment/features/customer/models/course_model.dart';

class CustomerCreateCourseViewmodel extends ChangeNotifier {
  bool _isLoading = false;
  bool get isLoading => _isLoading;
  
  Future<bool> createCourse({
    required String title,
    required String description,
    required String category,
    required DateTime scheduledTime,
    double price=0.0,
  }) async {
    _isLoading = true;
    notifyListeners();

    try {
      String uid = FirebaseAuth.instance.currentUser?.uid ?? '';
      if (uid.isEmpty) return false;

      String tutorName = 'Community Mentor';
      DocumentSnapshot userDoc = await FirebaseFirestore.instance.collection('users').doc(uid).get();
      if (userDoc.exists && userDoc.data() != null) {
        final userData = userDoc.data() as Map<String, dynamic>;
        tutorName = userData['username'] ?? 'Community Mentor';
      }

      String uniqueTimestamp=DateTime.now().millisecondsSinceEpoch.toString();
      String autogeneratedLink='https://meet.jit.si/Codementor_$uniqueTimestamp';

      final newCourse = CourseModel(
        id: '',
        title: title,
        description: description,
        category: category,
        tutorName: tutorName,
        tutorId: uid,
        meetLink: autogeneratedLink,
        scheduledTime: scheduledTime,
        isBooked: false,
        price:price,
      );
      
      await FirebaseFirestore.instance.collection('courses').add(newCourse.toMap());
      return true;
    } catch (e) {
      print('Error Creating Course: $e');
      return false;
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
}