// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqkEuWQaGt9aih_3-7_ZzwlFRHwTTsyrQ',
    appId: '1:54135923263:web:faa0c0c5a6f0d142ef8e8a',
    messagingSenderId: '54135923263',
    projectId: 'maeassignment-bcbd1',
    authDomain: 'maeassignment-bcbd1.firebaseapp.com',
    storageBucket: 'maeassignment-bcbd1.firebasestorage.app',
    measurementId: 'G-JDHGL412FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyJHeijCLL08radtNC5WDZ3k-BT3q1ItE',
    appId: '1:54135923263:android:ebad318ca928cc96ef8e8a',
    messagingSenderId: '54135923263',
    projectId: 'maeassignment-bcbd1',
    storageBucket: 'maeassignment-bcbd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKaRXSHb7hoK_iyien76YbV1nxTGBZrQ',
    appId: '1:54135923263:ios:351c75dd699374ecef8e8a',
    messagingSenderId: '54135923263',
    projectId: 'maeassignment-bcbd1',
    storageBucket: 'maeassignment-bcbd1.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgKaRXSHb7hoK_iyien76YbV1nxTGBZrQ',
    appId: '1:54135923263:ios:351c75dd699374ecef8e8a',
    messagingSenderId: '54135923263',
    projectId: 'maeassignment-bcbd1',
    storageBucket: 'maeassignment-bcbd1.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqkEuWQaGt9aih_3-7_ZzwlFRHwTTsyrQ',
    appId: '1:54135923263:web:ff13d5c0ef6c08fdef8e8a',
    messagingSenderId: '54135923263',
    projectId: 'maeassignment-bcbd1',
    authDomain: 'maeassignment-bcbd1.firebaseapp.com',
    storageBucket: 'maeassignment-bcbd1.firebasestorage.app',
    measurementId: 'G-FF4H5G9Q4D',
  );
}
